application: djshouts
version: 21
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: media/
  expiration: '365d'
  secure: optional

- url: /.*
  script: djangoappengine/main/main.py
  login: optional

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
