application: djshouts
version: 6
runtime: python27
threadsafe: false
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: media/
  expiration: '365d'
  secure: optional

- url: /.*
  script: djangoappengine/main/main.py
  login: optional

libraries:
  - name: jinja2
    version: "2.6"
